language: node_js
node_js: 
  - "6"
  - "8"
  - "10"

os: [linux, osx]
dist: trusty
sudo: required

# by caching the npm local cache, instead of ./node_modules,
# we theoretically avoid accidentally having npm keep around
# old modules in the tree
 cache:
   directories:
    - $(npm config get cache)


before_install:
  - npm i -g npm@latest

install:
  - npm install

script:
  - npm test
